name: napari-env
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1=h7bae524_0
  - blosc=1.21.6=h5499902_0
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py310hb4ad77e_2
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h93a5062_5
  - c-blosc2=2.15.2=h069cb6c_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - charls=2.4.2=h13dd4ca_0
  - cjdk=0.4.1=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - freetype=2.13.3=hce30654_1
  - giflib=5.2.2=h93a5062_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - imagecodecs=2024.9.22=py310hdfa98f9_0
  - imglyb=2.1.0=pyhecae5ae_1
  - jgo=1.0.6=pyhd8ed1ab_1
  - jpype1=1.5.2=py310h7f4e7e6_0
  - jxrlib=1.1=h93a5062_3
  - labeling=0.1.14=pyhd8ed1ab_1
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libaec=1.1.3=hebf3989_0
  - libavif16=1.3.0=hf1e31eb_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=20.1.4=ha82da77_1
  - libdeflate=1.22=hd74edd7_0
  - libffi=3.4.2=h3422bc3_5
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - libhwy=1.2.0=h9a9ea7e_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h72d67bc_1
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libsqlite=3.46.0=hfb93653_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=hfb2fe0b_1
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=20.1.4=hdb05f8b_0
  - lz4-c=1.9.4=hb7217d7_0
  - matplotlib-base=3.10.3=py310hadbac3a_0
  - maven=3.9.9=hce30654_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=hb89a1cb_0
  - numpy=2.2.5=py310h4d83441_0
  - openjdk=11.0.26=h7c160ba_2
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.5.0=h81ee809_1
  - progressbar2=4.5.0=pyhd8ed1ab_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pycparser=2.22=pyh29332c3_1
  - pyimagej=1.6.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.14=h2469fbe_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-utils=3.9.1=pyhff2d567_1
  - python_abi=3.10=7_cp310
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h92ec313_1
  - requests=2.32.3=pyhd8ed1ab_1
  - scyjava=1.12.0=pyhd8ed1ab_0
  - setuptools=70.1.1=pyhd8ed1ab_0
  - snappy=1.2.1=h98b9ce2_1
  - svt-av1=3.0.2=h8ab69cd_0
  - tk=8.6.13=h5083fa2_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - unicodedata2=16.0.0=py310h078409c_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xarray=2025.4.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.2.6=h57fd34a_0
  - zfp=1.0.1=h1c5d8ea_2
  - zlib-ng=2.2.4=h13dfb9a_0
  - zstandard=0.23.0=py310h078409c_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - alabaster==0.7.16
      - annotated-types==0.7.0
      - anyio==4.4.0
      - apoc==0.12.0
      - app-model==0.3.1
      - appdirs==1.4.4
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - autopep8==2.3.1
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bokeh==3.8.1
      - build==1.2.1
      - cachey==0.2.1
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - comm==0.2.2
      - contourpy==1.2.1
      - czifile==2019.7.2
      - dask==2024.6.2
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.15
      - devbio-napari==0.11.0
      - docstring-parser==0.16
      - docutils==0.21.2
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - flexcache==0.3
      - flexparser==0.3.1
      - fonttools==4.53.1
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - fsspec==2024.6.1
      - funcsigs==1.0.2
      - h11==0.14.0
      - h5py==3.12.1
      - hdbscan==0.8.40
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - imagesize==1.4.1
      - importlib-metadata==8.0.0
      - in-n-out==0.2.1
      - iniconfig==2.0.0
      - ipycanvas==0.13.3
      - ipyevents==2.0.2
      - ipykernel==6.29.5
      - ipympl==0.9.4
      - ipython==8.26.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - jupytext==1.16.4
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - locket==1.0.0
      - loguru==0.7.3
      - magicgui==0.8.3
      - mako==1.3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - napari==0.6.0
      - napari-accelerated-pixel-and-object-classification==0.14.1
      - napari-animation==0.0.8
      - napari-assistant==0.4.11
      - napari-blob-detection==0.0.2
      - napari-brightness-contrast==0.1.8
      - napari-clusters-plotter==0.8.1
      - napari-console==0.1.3
      - napari-crop==0.1.9
      - napari-curtain==0.1.1
      - napari-czifile2==0.2.7
      - napari-folder-browser==0.1.4
      - napari-layer-details-display==0.1.5
      - napari-mouse-controls==0.1.3
      - napari-plot-profile==0.2.2
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.0a2
      - napari-plugin-search==0.1.4
      - napari-pyclesperanto-assistant==0.25.0
      - napari-pystackreg==0.1.4
      - napari-roi==0.1.8
      - napari-segment-blobs-and-things-with-membranes==0.3.12
      - napari-simpleitk-image-processing==0.4.9
      - napari-skimage-regionprops==0.10.1
      - napari-stl-exporter==0.1.5
      - napari-svg==0.2.0
      - napari-tabu==0.1.5
      - napari-time-slicer==0.5.0
      - napari-tools-menu==0.1.20
      - napari-workflow-inspector==0.2.2
      - napari-workflow-optimizer==0.1.4
      - napari-workflows==0.2.11
      - narwhals==2.14.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - npe2==0.7.8
      - numba==0.61.2
      - numpydoc==1.7.0
      - ome-types==0.6.1
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.4.0
      - pint==0.24.1
      - pip==25.3
      - platformdirs==4.2.2
      - platymatch==0.0.3
      - pluggy==1.5.0
      - pooch==1.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - psygnal==0.11.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyabf==2.3.8
      - pyclesperanto==0.14.2
      - pyclesperanto-prototype==0.24.5
      - pycodestyle==2.12.1
      - pyconify==0.1.6
      - pydantic==2.8.2
      - pydantic-compat==0.1.2
      - pydantic-core==2.20.1
      - pydantic-extra-types==2.10.4
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyopencl==2024.3
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyperclip==1.9.0
      - pyproject-hooks==1.1.0
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.14
      - pyqt5-sip==12.13.0
      - pyqtgraph==0.13.7
      - pystackreg==0.2.8
      - pytab==1.0.4
      - pytest==8.3.3
      - python-bioformats==4.1.0
      - python-json-logger==2.0.7
      - pytools==2024.1.19
      - pytz==2024.1
      - pyvis==0.3.2
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - redlionfish==0.10
      - referencing==0.35.1
      - reikna==0.8.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scikit-posthocs==0.10.0
      - scipy==1.14.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shellingham==1.5.4
      - sidetable==0.9.1
      - simpleitk==2.4.0
      - six==1.16.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stack-data==0.6.3
      - stackview==0.12.1
      - statsmodels==0.14.4
      - superqt==0.6.7
      - tabulate==0.9.0
      - terminado==0.18.1
      - the-segmentation-game==0.2.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.2
      - tinycss2==1.3.0
      - toml==0.10.2
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transforms3d==0.4.2
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==2.2.2
      - vedo==2024.5.2
      - vispy==0.14.3
      - vtk==9.4.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - wordcloud==1.9.4
      - wrapt==1.16.0
      - xsdata==24.3.1
      - xyzservices==2025.11.0
      - zipp==3.19.2
prefix: /opt/anaconda3/envs/napari-env
